### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by SupKelelawar** [weserv/images#393]
hello sir, why this image return 404? please help, thanks sir 🙏

https://images.weserv.nl/?w=300&q=70&url=https://svr4.imgkc1.my.id/wp-content/img/L/Lord-of-Nine-Arts/032/001.jpg

**Comment by andrieslouw** [comment]
Hi, because the original image is also returning a 404-error, at least when I check it: https://svr4.imgkc1.my.id/wp-content/img/L/Lord-of-Nine-Arts/032/001.jpg

Redbot says the same: https://redbot.org/?uri=https://svr4.imgkc1.my.id/wp-content/img/L/Lord-of-Nine-Arts/032/001.jpg

The service needs the original image to work.

**Comment by SupKelelawar** [comment]
![Screenshot_20231022-214352](https://github.com/weserv/images/assets/138984997/219edfea-6d8a-4fbd-8df9-1756b44d9ce6)
but original image show normal on mobile sir (original)

**Comment by andrieslouw** [comment]
This image has a regional block, please contact the webmaster of imgkc1.my.id. See for example: https://tools.keycdn.com/performance?url=https://svr4.imgkc1.my.id/wp-content/img/L/Lord-of-Nine-Arts/032/001.jpg

![Screenshot_2023-10-22-18-03-42-90_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/weserv/images/assets/11487455/b64298dd-cabc-4e9a-81ba-b72a68dfdcaa)

**Comment by SupKelelawar** [comment]
ok, thanks for your info sir 🙏
